### ISSUE TITLE
Shift firebase DB URL to creds file

### ISSUE THREAD

**Issue by divanshujain** [AbdulMuhsinSE/graphql-mongo-firebaseauth-boilerplate#3]
https://github.com/AbdulMuhsinSE/graphql-mongo-firebaseauth-boilerplate/blob/f00217e67c3b97689fe2e63b2b7aa3409d163b54/utils.js#L114

This can be shifted to the creds json file for easier configuration.

**Comment by AbdulMuhsinSE** [comment]
That's definitely a good point. Do you think switching it to the creds file would make more sense or to the .env file? Cause I wouldn't want people to have to change the creds json file since they download it from Firebase directly.

**Comment by divanshujain** [comment]
yeah the creds file comes preset so .env makes sense.

**Comment by AbdulMuhsinSE** [comment]
Updated the project such that it is now read from the .env file
