### ISSUE TITLE
Function use unclear

### ISSUE THREAD

**Issue by divanshujain** [AbdulMuhsinSE/graphql-mongo-firebaseauth-boilerplate#4]
https://github.com/AbdulMuhsinSE/graphql-mongo-firebaseauth-boilerplate/blob/f00217e67c3b97689fe2e63b2b7aa3409d163b54/mongoose/user.js#L44

This function use isn't clear. If it's a test function, then you could keep the testing functions separate maybe. Otherwise, a comment would also do.

**Comment by AbdulMuhsinSE** [comment]
Added a couple of comments to describe what the exact functionality is. I have delegated not to rename the function for the time being because the user information creation is still happening within the mongoDB instance, and I cannot think of a better name that wouldn't be overwhelmingly verbose.
